//AUTH
// ** Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const ONLINE = 'ONLINE';
export const OFFLINE = 'OFFLINE';

// ** Register
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
// ** Forgot Password
export const FORGOT_REQUEST = 'FORGOT_REQUEST';
export const FORGOT_SUCCESS = 'FORGOT_SUCCESS';
export const FORGOT_FAILURE = 'FORGOT_FAILURE';
// ** Reset Password
export const RESET_REQUEST = 'RESET_REQUEST';
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_FAILURE = 'RESET_FAILURE';

//CREATE AN AD

export const STORAGE_REQUEST = 'STORAGE_REQUEST';
export const STORAGE_SUCCESS = 'STORAGE_SUCCESS';
export const STORAGE_FAILURE = 'STORAGE_FAILURE';

export const CREATEPOST_REQUEST = 'CREATEPOST_REQUEST';
export const CREATEPOST_SUCCESS = 'CREATEPOST_SUCCESS';
export const CREATEPOST_FAILURE = 'CREATEPOST_FAILURE';

export const FETCHPOST_REQUEST = 'FETCHPOST_REQUEST';
export const FETCHPOST_SUCCESS = 'FETCHPOST_SUCCESS';
export const FETCHPOST_FAILURE = 'FETCHPOST_FAILURE';

export const LIKEPOST_REQUEST = 'LIKEPOST_REQUEST';
export const LIKEPOST_SUCCESS = 'LIKEPOST_SUCCESS';
export const LIKEPOST_FAILURE = 'LIKEPOST_FAILURE';

export const USERPOST_REQUEST = 'USERPOST_REQUEST';
export const USERPOST_SUCCESS = 'USERPOST_SUCCESS';
export const USERPOST_FAILURE = 'USERPOST_FAILURE';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE';

export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';

export const CREATE_COMMENTS_REQUEST = 'CREATE_COMMENTS_REQUEST';
export const CREATE_COMMENTS_SUCCESS = "CREATE_COMMENTS_SUCCESS";
export const CREATE_COMMENTS_FAILURE = 'CREATE_COMMENTS_FAILURE';

export const EDITAD_REQUEST = 'EDITAD_REQUEST';
export const EDITAD_SUCCESS = 'EDITAD_SUCCESS';
export const EDITAD_FAILURE = 'EDITAD_FAILURE';

export const SET_ACTIVE_REEL = "SET_ACTIVE_REEL";

//DELETE MY ADS

export const DELETEAD_REQUEST = 'DELETEAD_REQUEST';
export const DELETEAD_SUCCESS = 'DELETEAD_SUCCESS';
export const DELETEAD_FAILURE = 'DELETEAD_FAILURE';

//PROFILE

export const PROFILE_EDIT_REQUEST = 'PROFILE_EDIT_REQUEST';
export const PROFILE_EDIT_SUCCESS = 'PROFILE_EDIT_SUCCESS';
export const PROFILE_EDIT_FAILURE = 'PROFILE_EDIT_FAILURE';


//SLOTS

export const RECUR_SLOTS_UPDATE_REQUEST = "RECUR_SLOTS_UPDATE_REQUEST";
export const RECUR_SLOTS_UPDATE_SUCCESS = "RECUR_SLOTS_UPDATE_SUCCESS";
export const RECUR_SLOTS_UPDATE_FAILURE = "RECUR_SLOTS_UPDATE_FAILURE";

export const BOOOKSLOT_REQUEST = 'BOOOKSLOT_REQUEST';
export const BOOOKSLOT_SUCCESS = 'BOOOKSLOT_SUCCESS';
export const BOOOKSLOT_FAILURE = 'BOOOKSLOT_FAILURE';

//SCHEDULER

export const GET_SCHEDULED_SLOTS_R = "GET_SCHEDULED_SLOTS_R";
export const GET_SCHEDULED_SLOTS_S = "GET_SCHEDULED_SLOTS_S";
export const GET_SCHEDULED_SLOTS_F = "GET_SCHEDULED_SLOTS_F";

export const API_REQUEST = "API_REQUEST";
export const API_SUCCESS = "API_SUCCESS";
export const API_FAILURE = "API_FAILURE";