export const Fonts = {
  Black: 'VisueltPro-Black',
  BlackItalic: 'VisueltPro-BlackItalic',
  Bold: 'VisueltPro-Bold',
  BoldItalic: 'VisueltPro-BoldItalic',
  XBold: 'VisueltPro-ExtraBold',
  XBoldItalic: 'VisueltPro-ExtraBoldItalic',
  Xlight: 'VisueltPro-ExtraLight',
  XlightItalic: 'VisueltPro-ExtraLightItalic',
  Medium: 'VisueltPro-Medium',
  MediumItalic: 'VisueltPro-MediumItalic',
  Regular: 'VisueltPro-Regular',
  SemiBold: 'VisueltPro-SemiBold',
  SemiBoldItalic: 'VisueltPro-SemiBoldItalic',
  Thin: 'VisueltPro-Thin',
  ThinItalic: 'VisueltPro-ThinItalic',
};
